# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcCotacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Valor Pago'),
        ),
    ]
