# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcCotacao', '0002_auto_20170324_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorder',
            name='jogo',
        ),
        migrations.RemoveField(
            model_name='itemorder',
            name='order',
        ),
        migrations.DeleteModel(
            name='ItemOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
